### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by jgeorge1983** [usernein/tv-card#6]
Sorry, am I being an idiot?
Do we add the custom buttons to the tv-card.js file?

I have added it to that file as below:

```
var custom_keys = {
  guide:
    icon: "mdiTelevisionGuide"
    key: KEY_GUIDE
  toggle_light:
    icon: "mdiLightbulb"
    service: light.toggle
    service_data:
      entity_id: light.bedroom_light
};
```

rebooted, cleared cache, but when I add it i just get a blank spot on the remote, the remote code looks like:
```
type: custom:tv-card
entity: media_player.living_room_tv
title: TV
power_row:
  - power
  - guide
  - toggle_light
channel_row:
  - channel_up
  - info
  - channel_down
volume_row: slider
source_row:
  - return
  - home
  - source
navigation_row: buttons
media_control_row:
  - rewind
  - play
  - pause
  - fast_forward
```

**Comment by mdb17** [comment]
I am just using the standard mdi icons and also getting blank buttons. Here is my code: 
`  - type: custom:tv-card
    entity: media_player.43_tcl_roku_tv
    #title: Example 2
    custom_keys:
      power:
        icon: "mdipower"
        action: call-service
        service: remote.toggle
        service_data:
          entity_id: remote.43_tcl_roku_tv

    power_row:
      - power
    channel_row:
      - channel_up
      - info
      - channel_down

The power buton is blank on two different devices.

**Comment by mdb17** [comment]
Yes, my button is working

**Comment by usernein** [comment]
> @jgeorge1983:
> Do we add the custom buttons to the tv-card.js file?

No, no. You set them in the card config, where you also set the layout (you called it remote code):
```yaml
type: custom:tv-card
entity: media_player.living_room_tv
title: TV
power_row:
  - power
  - guide
  - toggle_light
channel_row:
  - channel_up
  - info
  - channel_down
volume_row: slider
source_row:
  - return
  - home
  - source
navigation_row: buttons
media_control_row:
  - rewind
  - play
  - pause
  - fast_forward
custom_keys:
  guide:
    icon: "mdiTelevisionGuide"
    key: KEY_GUIDE
  toggle_light:
    icon: "mdiLightbulb"
    service: light.toggle
    service_data:
      entity_id: light.bedroom_light
```

You don't need to touch the .js files for any setting, everything is customized in the card config

**Comment by ajurna** [comment]
just to confirm the buttons work in my example too, just no icon.

**Comment by usernein** [comment]
> @mdb17:
> The power buton is blank on two different devices.

That's because the icon names are case-sensitive. It's "`mdiPower`", not "`mdipower`"
Also, there's no "`action`" inside the [custom buttons params](https://github.com/usernein/tv-card#custom-buttons). But that's not a problem, the card will just ignore the unnecessary param

**Comment by mdb17** [comment]
> > @mdb17:
> > The power buton is blank on two different devices.
> 
> That's because the icon names are case-sensitive. It's "`mdiPower`", not "`mdipower`" Also, there's no "`action`" inside the [custom buttons params](https://github.com/usernein/tv-card#custom-buttons). But that's not a problem, the card will just ignore the unnecessary param

That fixed it, thanks! I am not sure I follow you on the action comment though.

**Comment by usernein** [comment]
> This card currently only supports icons from [MDI](https://materialdesignicons.com/)

I've just released [v0.5.0](https://github.com/usernein/tv-card/releases/tag/v.0.5.0) and this is not true anymore. You can now use [SimpleIcons](https://github.com/vigonotion/hass-simpleicons) and [FontAwesome](https://github.com/thomasloven/hass-fontawesome) easier, without touching svg paths and custom_icons.

Just install the integrations and you'll be able to use them:
```yaml
custom_keys:
  guide:
    icon: fas:heart
    key: KEY_GUIDE
custom_sources:
  plex:
    icon: si:plex
    source: Plex
```

If you upgrade to v0.5.0, remember to rename your old icons from MDI to the new format, e.g. `mdiTelevisionGuide` -> `mdi:television-guide`, `mdiPower` -> `mdi:power`

**Comment by ajurna** [comment]
seems to be fixed in v0.5.0. thanks!

**Comment by ickam** [comment]
Hi, 
So I still have a problem
my code is this:

`type: custom:tv-card
entity: media_player.samsung
title: Samsung
power_row:
  - power
channel_row:
  - channel_up
  - info
  - channel_down
custom_sources:
  emby:
    icon: si:emby
    source: emby
  youtube:
    icon: si:youtube
    source: Youtube
  bbc:
    icon: si:bbciplayer
    source: bbc
  Netflix:
    icon: si:netflix
    source: netflix
volume_row: buttons
navigation_row: buttons
source_row:
  - return
  - home
  - source
media_control_row:
  - rewind
  - play
  - pause
  - fast_forward`

but I am still not getting the app icons. Can you help @usernein ?
